name: Docker Image CI and Version Bump

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Check if commit is a version bump
      id: check_version_bump
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Last commit message: $COMMIT_MESSAGE"
        if [[ "$COMMIT_MESSAGE" == *"Bump version"* ]]; then
          echo "is_version_bump=true" >> $GITHUB_OUTPUT
        else
          echo "is_version_bump=false" >> $GITHUB_OUTPUT
        fi

    - name: Read current version
      id: current_version
      run: |
        VERSION=$(cat version.txt)
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      if: steps.check_version_bump.outputs.is_version_bump == 'true'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build . --file Dockerfile --tag godver3/cli_debrid:${{ steps.current_version.outputs.version }} --tag godver3/cli_debrid:dev
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push godver3/cli_debrid:${{ steps.current_version.outputs.version }}
        docker push godver3/cli_debrid:dev

    - name: Increment version and create PR
      if: steps.check_version_bump.outputs.is_version_bump == 'false'
      run: |
        # Increment version
        VERSION=$(cat version.txt)
        NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        echo "New version: $NEW_VERSION"
        
        # Create new branch
        git checkout -b version-bump-$NEW_VERSION
        
        # Update version.txt
        echo $NEW_VERSION > version.txt
        
        # Commit and push
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.txt
        git commit -m "Bump version to $NEW_VERSION"
        git push origin version-bump-$NEW_VERSION
        
        # Create PR
        gh pr create --base dev --head version-bump-$NEW_VERSION --title "Bump version to $NEW_VERSION" --body "Automated version bump"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
