name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "version.txt"
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Check if commit is a version bump
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Last commit message: $COMMIT_MESSAGE"
        if [[ "$COMMIT_MESSAGE" == *"Bump version"* ]]; then
          echo "Skipping build for version bump commit."
          exit 0
        fi

    - name: Read and increment version
      id: version
      run: |
        VERSION=$(cat version.txt)
        echo "Current version: $VERSION"
        NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        echo "New version: $NEW_VERSION"
        echo $NEW_VERSION > version.txt
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Create version bump branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b version-bump-${{ steps.version.outputs.new_version }}
        git add version.txt
        git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"
        git push origin version-bump-${{ steps.version.outputs.new_version }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_TOKEN }}
        commit-message: Bump version to ${{ steps.version.outputs.new_version }}
        title: Bump version to ${{ steps.version.outputs.new_version }}
        body: Automated version bump
        branch: version-bump-${{ steps.version.outputs.new_version }}
        base: dev

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag godver3/cli_debrid:${{ steps.version.outputs.new_version }} --tag godver3/cli_debrid:dev

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |
        docker push godver3/cli_debrid:${{ steps.version.outputs.new_version }}
        docker push godver3/cli_debrid:dev
